version: '3'

networks:
  default:
    driver: bridge

services:
  db:
    image: postgres:13.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nfl_rushing_dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5344:5432

volumes:
  db-data:
    driver: local
